#ifdef INSIGHT_MATRIX_FUNC
#undef INSIGHT_MATRIX_FUNC
#endif

#ifdef INSIGHT_MATRIX_TYPE
#undef INSIGHT_MATRIX_TYPE
#endif

#ifdef CONCAT3
#undef CONCAT3
#endif

#ifdef CONCAT3x
#undef CONCAT3x
#endif

#ifdef CONCAT2
#undef CONCAT2
#endif

#ifdef CONCAT2x
#undef CONCAT2x
#endif

#ifdef INSIGHT_MATRIX_OUTPUT_FORMAT
#undef INSIGHT_MATRIX_OUTPUT_FORMAT
#endif

#ifdef INSIGHT_MATRIX_INPUT_FORMAT
#undef INSIGHT_MATRIX_INPUT_FORMAT
#endif

#ifdef INSIGHT_MATRIX_ELEM_ONE
#undef INSIGHT_MATRIX_ELEM_ONE
#endif

#ifdef INSIGHT_MATRIX_ELEM_ZERO
#undef INSIGHT_MATRIX_ELEM_ZERO
#endif

#ifdef INSIGHT_MATRIX_ELEM_TYPE
#undef INSIGHT_MATRIX_ELEM_TYPE
#endif
